### ISSUE TITLE
Add app_id to to apps_to_delete in the sending of the results of an install operation

### ISSUE THREAD

**Issue by linuxdynasty** [vFense/vFenseAgent-win#12]
Currently you are sending the app_name and app_version, I would also like the agent to include the app_id of the application. Since the app_id is generated by add the app_name + app_version, the agent can generate it instead of the server doing it. Since we do not want to continue to bog down the server with the app_id generation.

**Comment by RafaelGonzalez84** [comment]
Linux agent, none related to the Windows agent.
