### ISSUE TITLE
Update Operation freezes

### ISSUE THREAD

**Issue by MarcusCaepio** [vFense/vFenseAgent-win#15]
Since 2 hours I got a freezed updateoperation with the supported apps. See Screenshot below.

Kind regards
Marcus
![bildschirmfoto 2014-05-06 um 16 00 19](https://cloud.githubusercontent.com/assets/7324088/2890224/319749d4-d527-11e3-93df-8e6668cca0e3.png)

**Comment by RafaelGonzalez84** [comment]
The team and my self have fixed what appeared to be the issue, i've tested it and everything seems to be working fine.
Java does required a reboot and it pops up a prompt which if no ones closes it will prevent the installs from going forward.
