### ISSUE TITLE
Fix OperationManager empty "data" on json

### ISSUE THREAD

**Issue by RafaelGonzalez84** [vFense/vFenseAgent-win#18]
Need to fix Agent.Core.ServerOperations.OperatoinManager.cs
On the method for major failure while generating the json, field "data" is been generated manually as a string and causing the server to respond with an error and not update the UI correct. 
Did a quick fix by adding new method called emptyData().

**Comment by ghost** [comment]
@RafaelGonzalez84  Is this issue resolved?
