### ISSUE TITLE
Operations will now contain the response uri and request method

### ISSUE THREAD

**Issue by hchac** [vFense/vFenseAgent-win#7]
toppatch/vFense#46

Remove all the hardcoding that has been done and modify the code to take advantage of the new keys.

**Comment by RafaelGonzalez84** [comment]
requirements have been changed 
toppatch/vFense#46

**Comment by RafaelGonzalez84** [comment]
all the commits used for response uri with the different api calls.
1ec75b2033b3df8b0e00fc01d45c687f9bbd82d7
2403e5e3c0ab39a9b7c16576f9fbbd1e773bced7
b1ac1187834c9e4900878f19cd4ff42ec0b2a8a6
1399d5e10b14d1120b1d08e4b62483b62b617926
4a61bd399230a3e17b16213781148dd1080e8b62
2c95d0aa4e1f35d1f917fa4317875b383ed3361b
409b150e0530533b12d8c11b93219bd35ff3d1a0
8f3b474e0b5e8e6d224113fc8b8f1f7c392efe68
0c7e247a2591f7e9062aa42f79796282449d013b
6477ccac50afec4c8e3bcbc33485c8c32603db4b
fc48e023317510927c73777b57d8c4bce49ee919
01dd1bec36968e22997108c9cfd0b15af7855898
4761ac0de03ec86163e61b3e78d0ff54a29139ae
